import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { pathToFileURL } from "node:url";
import { randomUUID } from "node:crypto";
import assert from "node:assert/strict";
import postgres from "postgres";
import ts from "typescript";
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"origo-qa-"));
for(const name of ["validation","import-data"]) fs.writeFileSync(path.join(tmp,name+".mjs"),ts.transpile(fs.readFileSync("src/lib/"+name+".ts","utf8"),{module:ts.ModuleKind.ESNext}).replace('"./validation"','"./validation.mjs"'));
const {parseMoney,calendarDate,validatePeriod}=await import(pathToFileURL(path.join(tmp,"validation.mjs")));
const {importPayload}=await import(pathToFileURL(path.join(tmp,"import-data.mjs")));
assert.equal(parseMoney("1.234,56"),1234.56);assert.equal(parseMoney("1.234"),1234);assert.equal(parseMoney("0"),0);
assert.equal(parseMoney("1234.56"),1234.56);assert.throws(()=>parseMoney("-10"));
assert.equal(calendarDate("29/02/2024"),"2024-02-29");assert.throws(()=>calendarDate("31/02/2026"));assert.throws(()=>validatePeriod("2026-10-01","2026-09-01"));
assert.deepEqual(importPayload({serial:"QA"},"ativos"),{serial_number:"QA"});
assert.deepEqual(importPayload({serial:"QA",marca:"",modelo:"[LIMPAR]",custo_mensal:0},"ativos"),{serial_number:"QA",model:null,monthly_cost:0});
console.log("PASS: monetary values, valid dates, partial import preservation and explicit clearing");

fs.writeFileSync(path.join(tmp,'excel.mjs'),ts.transpile(fs.readFileSync('src/lib/excel.ts','utf8'),{module:ts.ModuleKind.ESNext}).replaceAll('import("xlsx")','import('+JSON.stringify(pathToFileURL(path.resolve('node_modules/xlsx/xlsx.mjs')).href)+')'));
const {readSpreadsheet}=await import(pathToFileURL(path.join(tmp,'excel.mjs')));
const csvBytes=fs.readFileSync('scripts/qa-import-preview.csv');
const csvRows=await readSpreadsheet(csvBytes.buffer.slice(csvBytes.byteOffset,csvBytes.byteOffset+csvBytes.byteLength));
assert.equal(importPayload(csvRows[0],'ativos').monthly_cost,1234.56);
assert.equal(importPayload(csvRows[0],'ativos').lease_start,'2026-01-01');
assert.throws(()=>importPayload(csvRows[1],'ativos'),/Data inválida/);
console.log('PASS: actual CSV reader preserves Brazilian amounts and calendar dates');

const db=postgres({host:"127.0.0.1",port:54330,database:"origo_workflow_test",username:"postgres",password:fs.readFileSync(path.join(process.env.LOCALAPPDATA,"origoassetmanagement-local/admin-password.local"),"utf8")});
assert.equal((await db`select current_database() n`)[0].n,"origo_workflow_test");
const actor=randomUUID(),viewer=randomUUID(),employee=randomUUID(),asset=randomUUID(),other=randomUUID(),template=randomUUID();
const checks=[{label:"Conferido",ok:true}];
const asUser=(id,fn)=>db.begin(async tx=>{await tx`select set_config('request.jwt.claim.sub',${id},true)`;await tx`set local role authenticated`;return fn(tx);});
const call=(action,data)=>asUser(actor,tx=>tx`select qa_transaction(${action},${tx.json(data)}) result`);
try {
 await db`insert into profiles(id,email) values(${actor},'qa@example.test'),(${viewer},'viewer@example.test')`;
 await db`insert into user_roles(user_id,role) values(${actor},'admin'),(${viewer},'colaborador')`;
 await db`insert into employees(id,full_name,email) values(${employee},'QA fixture',${employee+'@example.test'})`;
 await db`insert into assets(id,serial_number,model,monthly_cost,lease_start,lease_end,location) values(${asset},${asset},'Preservar',12.34,'2026-01-01','2026-12-31','QA'),(${other},${other},'Outro',99,'2026-02-01','2027-12-31','QA')`;
 await db`insert into agreement_templates(id,name,body) values(${template},'QA','Termo QA')`;
 await assert.rejects(asUser(actor,tx=>tx`update assets set status='em_uso' where id=${asset}`),/vínculo ativo/);
 const assignment=randomUUID();
 await asUser(actor,tx=>tx`select create_assignment_complete(${assignment},${asset},${employee},now(),'Bom','',${template},'Termo QA',${tx.json(checks)},ARRAY[]::text[])`);
 await assert.rejects(asUser(actor,tx=>tx`update assets set status='disponivel' where id=${asset}`),/devolução/);
 await assert.rejects(call('transfer',{id:assignment,new_id:randomUUID(),employee_id:randomUUID(),template_id:template,content:'Termo QA',items:checks}),/Colaborador/);
 assert.equal((await db`select status from assignments where id=${assignment}`)[0].status,'ativo');
 await call('return',{id:assignment,condition:'Bom',items:checks,photos:[]});
 await call('undo_return',{id:assignment});
 await call('return',{id:assignment,condition:'Bom',items:checks,photos:[]});
 assert.equal((await db`select actor_email from audit_log where entity_id=${assignment} limit 1`)[0].actor_email,'qa@example.test');
 console.log('PASS: status invariants, transfer rollback, return/undo and audit attribution');
 await call('contract',{ids:[asset,other],patch:{supplier:'Novo fornecedor',contract_number:'QA'}});
 const amounts=await db`select monthly_cost,lease_end from assets where id in (${asset},${other}) order by monthly_cost`;
 assert.equal(Number(amounts[0].monthly_cost),12.34);assert.equal(Number(amounts[1].monthly_cost),99);
 await assert.rejects(call('contract',{ids:[asset,other],patch:{monthly_cost:-1}}),/negativo/);
 assert.equal(Number((await db`select monthly_cost from assets where id=${asset}`)[0].monthly_cost),12.34);
 const batch=randomUUID();
 await asUser(actor,tx=>tx`select prepare_import(${batch},'ativos','qa.xlsx',${tx.json([{serial_number:asset,supplier:'Importado'}, {serial_number:other,monthly_cost:0}])})`);
 for(const line of [2,2,3])await asUser(actor,tx=>tx`select apply_import_row(${batch},${line})`);
 await asUser(actor,tx=>tx`select finish_import(${batch})`);
 assert.equal((await db`select model from assets where id=${asset}`)[0].model,'Preservar');
 assert.equal(Number((await db`select monthly_cost from assets where id=${other}`)[0].monthly_cost),0);
 assert.equal((await db`select updated_rows from import_batches where id=${batch}`)[0].updated_rows,2);
 console.log('PASS: heterogeneous contract values, atomic rejection and resumable import without duplicate application');
 await asUser(actor,tx=>tx`select set_access_roles_atomic(${viewer},ARRAY['gestor'])`);
 await assert.rejects(asUser(actor,tx=>tx`select set_access_roles_atomic(${viewer},ARRAY['invalid'])`),/válidos/);
 assert.equal((await db`select role from user_roles where user_id=${viewer}`)[0].role,'gestor');
 const invite=randomUUID();
 await assert.rejects(asUser(actor,tx=>tx`select finalize_access_invite(${invite},'qa-invite@origoenergia.com.br','QA',ARRAY['invalid'])`),/válidos/);
 assert.equal((await db`select count(*)::int n from profiles where id=${invite}`)[0].n,0);
 await asUser(actor,tx=>tx`select finalize_access_invite(${invite},'qa-invite@origoenergia.com.br','QA',ARRAY['colaborador'])`);
 await asUser(actor,tx=>tx`select allow_email_atomic('qa-invite@origoenergia.com.br','QA',ARRAY['gestor'],'teste')`);
 await asUser(actor,tx=>tx`select allow_email_atomic('qa-invite@origoenergia.com.br','QA',ARRAY['gestor'],'teste')`);
 assert.equal((await db`select count(*)::int n from user_roles where user_id=${invite} and role='gestor'`)[0].n,1);
 console.log('PASS: invite transaction rollback and repeatable allowlisting');
 const ag=(await db`select id from agreements where assignment_id=${assignment}`)[0].id;
 const key=(await asUser(actor,tx=>tx`select claim_agreement_dispatch(${ag}) k`))[0].k;
 await assert.rejects(asUser(actor,tx=>tx`select claim_agreement_dispatch(${ag})`),/já solicitado/);
 await call('dispatch_finish',{id:ag,key,envelope_id:'qa-envelope'});
 assert.equal((await db`select status from agreements where id=${ag}`)[0].status,'enviado');
 await call('attach_signed',{id:ag,path:'qa/document.pdf',name:'test.pdf'});
 await call('attach_signed',{id:ag,path:'qa/document.pdf',name:'test.pdf'});
 assert.equal(Number((await db`select count(*) n from documents where agreement_id=${ag}`)[0].n),1);
 await db`select apply_signature_webhook(${db.json({id:ag,status:'enviado',envelope_id:'qa-envelope'})})`;
 assert.equal((await db`select status from agreements where id=${ag}`)[0].status,'assinado');
 const webhookAgreement=randomUUID();await db`insert into agreements(id,employee_id,asset_id,assignment_id,content) values(${webhookAgreement},${employee},${asset},${assignment},'QA callback')`;
 const notification={id:webhookAgreement,status:'assinado',envelope_id:'callback-test',path:'qa/callback.pdf',name:'callback.pdf'};
 await db`select apply_signature_webhook(${db.json(notification)})`;
 await db`select apply_signature_webhook(${db.json(notification)})`;
 assert.equal((await db`select count(*)::int n from documents where agreement_id=${webhookAgreement}`)[0].n,1);
 await assert.rejects(asUser(actor,tx=>tx`select apply_signature_webhook(${tx.json(notification)})`),/permission denied/);
 console.log('PASS: webhook replay, signed state cannot regress, restricted webhook RPC');
 console.log('PASS: role replacement, dispatch claim blocks duplicates and signed attachment is idempotent');
 const session=randomUUID(),location='QA-'+session;
 await db`insert into assets(serial_number,location) select ${location}||'-'||g,${location} from generate_series(1,1105) g`;
 await asUser(actor,tx=>tx`insert into inventory_sessions(id,name,scope) values(${session},'QA volume',${tx.json({location})})`);
 await asUser(actor,tx=>tx`insert into inventory_checks(session_id,asset_id,checked_by) select ${session},id,${actor} from assets where location=${location}`);
 await db`insert into assets(serial_number,location) values(${location+'-new'},${location})`;
 assert.equal(Number((await db`select jsonb_array_length(snapshot) n from inventory_sessions where id=${session}`)[0].n),1105);
 await asUser(actor,tx=>tx`update inventory_sessions set status='encerrada',closed_at=now() where id=${session}`);
 assert.equal((await call('inventory_missing',{id:session}))[0].result.count,0);
 await assert.rejects(asUser(actor,tx=>tx`insert into inventory_checks(session_id,asset_id) values(${session},${asset})`),/encerrada/);
 console.log('PASS: 1105 checks, frozen scope, no false missing assets and closed-session immutability');
} finally {await db.end();}

