/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated/administracao'
import { Route as AuthenticatedAtivosRouteImport } from './routes/_authenticated/ativos'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedImportacaoRouteImport } from './routes/_authenticated/importacao'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPessoasRouteImport } from './routes/_authenticated/pessoas'
import { Route as AuthenticatedTermosRouteImport } from './routes/_authenticated/termos'
import { Route as AuthenticatedVinculosRouteImport } from './routes/_authenticated/vinculos'
import { Route as AuthenticatedAtivosIdRouteImport } from './routes/_authenticated/ativos.$id'
import { Route as AuthenticatedPessoasIdRouteImport } from './routes/_authenticated/pessoas.$id'
import { Route as ApiPublicHermesAssinaturaRouteImport } from './routes/api/public/hermes.assinatura'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAtivosRoute = AuthenticatedAtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportacaoRoute = AuthenticatedImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPessoasRoute = AuthenticatedPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTermosRoute = AuthenticatedTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVinculosRoute = AuthenticatedVinculosRouteImport.update({
  id: '/vinculos',
  path: '/vinculos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtivosIdRoute = AuthenticatedAtivosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAtivosRoute,
} as any)
const AuthenticatedPessoasIdRoute = AuthenticatedPessoasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPessoasRoute,
} as any)
const ApiPublicHermesAssinaturaRoute =
  ApiPublicHermesAssinaturaRouteImport.update({
    id: '/api/public/hermes/assinatura',
    path: '/api/public/hermes/assinatura',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/ativos': typeof AuthenticatedAtivosRouteWithChildren
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pessoas': typeof AuthenticatedPessoasRouteWithChildren
  '/termos': typeof AuthenticatedTermosRoute
  '/vinculos': typeof AuthenticatedVinculosRoute
  '/ativos/$id': typeof AuthenticatedAtivosIdRoute
  '/pessoas/$id': typeof AuthenticatedPessoasIdRoute
  '/api/public/hermes/assinatura': typeof ApiPublicHermesAssinaturaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/ativos': typeof AuthenticatedAtivosRouteWithChildren
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pessoas': typeof AuthenticatedPessoasRouteWithChildren
  '/termos': typeof AuthenticatedTermosRoute
  '/vinculos': typeof AuthenticatedVinculosRoute
  '/ativos/$id': typeof AuthenticatedAtivosIdRoute
  '/pessoas/$id': typeof AuthenticatedPessoasIdRoute
  '/api/public/hermes/assinatura': typeof ApiPublicHermesAssinaturaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/ativos': typeof AuthenticatedAtivosRouteWithChildren
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/importacao': typeof AuthenticatedImportacaoRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pessoas': typeof AuthenticatedPessoasRouteWithChildren
  '/_authenticated/termos': typeof AuthenticatedTermosRoute
  '/_authenticated/vinculos': typeof AuthenticatedVinculosRoute
  '/_authenticated/ativos/$id': typeof AuthenticatedAtivosIdRoute
  '/_authenticated/pessoas/$id': typeof AuthenticatedPessoasIdRoute
  '/api/public/hermes/assinatura': typeof ApiPublicHermesAssinaturaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/administracao'
    | '/ativos'
    | '/auditoria'
    | '/importacao'
    | '/integracoes'
    | '/painel'
    | '/pessoas'
    | '/termos'
    | '/vinculos'
    | '/ativos/$id'
    | '/pessoas/$id'
    | '/api/public/hermes/assinatura'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/administracao'
    | '/ativos'
    | '/auditoria'
    | '/importacao'
    | '/integracoes'
    | '/painel'
    | '/pessoas'
    | '/termos'
    | '/vinculos'
    | '/ativos/$id'
    | '/pessoas/$id'
    | '/api/public/hermes/assinatura'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/administracao'
    | '/_authenticated/ativos'
    | '/_authenticated/auditoria'
    | '/_authenticated/importacao'
    | '/_authenticated/integracoes'
    | '/_authenticated/painel'
    | '/_authenticated/pessoas'
    | '/_authenticated/termos'
    | '/_authenticated/vinculos'
    | '/_authenticated/ativos/$id'
    | '/_authenticated/pessoas/$id'
    | '/api/public/hermes/assinatura'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHermesAssinaturaRoute: typeof ApiPublicHermesAssinaturaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ativos': {
      id: '/_authenticated/ativos'
      path: '/ativos'
      fullPath: '/ativos'
      preLoaderRoute: typeof AuthenticatedAtivosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importacao': {
      id: '/_authenticated/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof AuthenticatedImportacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pessoas': {
      id: '/_authenticated/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AuthenticatedPessoasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/termos': {
      id: '/_authenticated/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof AuthenticatedTermosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vinculos': {
      id: '/_authenticated/vinculos'
      path: '/vinculos'
      fullPath: '/vinculos'
      preLoaderRoute: typeof AuthenticatedVinculosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ativos/$id': {
      id: '/_authenticated/ativos/$id'
      path: '/$id'
      fullPath: '/ativos/$id'
      preLoaderRoute: typeof AuthenticatedAtivosIdRouteImport
      parentRoute: typeof AuthenticatedAtivosRoute
    }
    '/_authenticated/pessoas/$id': {
      id: '/_authenticated/pessoas/$id'
      path: '/$id'
      fullPath: '/pessoas/$id'
      preLoaderRoute: typeof AuthenticatedPessoasIdRouteImport
      parentRoute: typeof AuthenticatedPessoasRoute
    }
    '/api/public/hermes/assinatura': {
      id: '/api/public/hermes/assinatura'
      path: '/api/public/hermes/assinatura'
      fullPath: '/api/public/hermes/assinatura'
      preLoaderRoute: typeof ApiPublicHermesAssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAtivosRouteChildren {
  AuthenticatedAtivosIdRoute: typeof AuthenticatedAtivosIdRoute
}

const AuthenticatedAtivosRouteChildren: AuthenticatedAtivosRouteChildren = {
  AuthenticatedAtivosIdRoute: AuthenticatedAtivosIdRoute,
}

const AuthenticatedAtivosRouteWithChildren =
  AuthenticatedAtivosRoute._addFileChildren(AuthenticatedAtivosRouteChildren)

interface AuthenticatedPessoasRouteChildren {
  AuthenticatedPessoasIdRoute: typeof AuthenticatedPessoasIdRoute
}

const AuthenticatedPessoasRouteChildren: AuthenticatedPessoasRouteChildren = {
  AuthenticatedPessoasIdRoute: AuthenticatedPessoasIdRoute,
}

const AuthenticatedPessoasRouteWithChildren =
  AuthenticatedPessoasRoute._addFileChildren(AuthenticatedPessoasRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedAtivosRoute: typeof AuthenticatedAtivosRouteWithChildren
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedImportacaoRoute: typeof AuthenticatedImportacaoRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPessoasRoute: typeof AuthenticatedPessoasRouteWithChildren
  AuthenticatedTermosRoute: typeof AuthenticatedTermosRoute
  AuthenticatedVinculosRoute: typeof AuthenticatedVinculosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedAtivosRoute: AuthenticatedAtivosRouteWithChildren,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedImportacaoRoute: AuthenticatedImportacaoRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPessoasRoute: AuthenticatedPessoasRouteWithChildren,
  AuthenticatedTermosRoute: AuthenticatedTermosRoute,
  AuthenticatedVinculosRoute: AuthenticatedVinculosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHermesAssinaturaRoute: ApiPublicHermesAssinaturaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
